---
title: "Most Frequent Emojis"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(readr)
library(magrittr)
library(DataCombine)
library(emojifont)
library(tidyverse)

emoticons <- read.csv("emoji_decoder.csv", header = T)
```

```{r Data, echo=FALSE}

emoji_data <- read_csv("./raw-data/emoji-responses.csv", 
                       col_types = cols(
                          Timestamp = col_character(),
                          `Please confirm that you are filling out this form on an iPhone before moving on with this study.` = col_character(),
                          `Graduation Year` = col_double(),
                          Gender = col_character(),
                          `What house do you live in?` = col_character(),
                          `What best describes your ethnicity?` = col_character(),
                          `Where is your hometown / current residence area outside of Harvard located?` = col_character(),
                          `(Intended) Concentration(s)` = col_character(),
                          `Secondary (if applicable)` = col_character(),
                          `Email Address` = col_character()
                       ))

emoji_data_count <- nrow(emoji_data)

# Renaming Columns

emoji_data %<>% 
  rename(time = "Timestamp",
         confirm = "Please confirm that you are filling out this form on an iPhone before moving on with this study.",
         emojis = "Type, in order, the first two columns from your 'frequently used' emoji section.",
         year = "Graduation Year",
         gender = "Gender",
         house = "What house do you live in?",
         ethnicity = "What best describes your ethnicity?",
         state = "Where is your hometown / current residence area outside of Harvard located?",
         concentration = "(Intended) Concentration(s)",
         secondary = "Secondary (if applicable)",
         email = "Email Address")

```

```{r Remove Double Spaces, echo = FALSE}

# Turn to normal data frame to work with

emoji_data <- as.data.frame(emoji_data)

emoji_data$emojis <- gsub("  ", "", emoji_data$emojis)

```

```{r Separate into Different Columns, echo = FALSE}
 
emoji_data %<>%
  separate(emojis, 
           c("e1", "e2", "e3", "e4", "e5", "e6", "e7", "e8", "e9", "e10", "other"), 
           sep = c(1,2,3,4,5,6,7,8,9,10), 
           remove = FALSE)

```

```{r Creating Rankings, echo = FALSE}
rankings <- emoji_data %>%
  group_by(e1) %>%
  count(e1) %>%
  arrange(desc(n)) %>%
  head(8)
```

```{r Graphing, echo = FALSE}

# Emojis from https://cran.r-project.org/web/packages/emojifont/vignettes/emojifont.html

emoji_labels <- data.frame(
  
  # From previous rankings df
  
  x=rankings$e1, 
  y=rankings$n,
  
  # Emojis from the emoji-search; not fully accurate as this package is not
  # up-to-date.
  
  label = c(emoji('heart'), 
            emoji("joy"), 
            emoji('sob'),
            emoji('heartbeat'),
            emoji('relaxed'),
            emoji('frowning'),
            emoji('heart_eyes'),
            emoji('triumph')))

ggplot(emoji_labels, aes(reorder(x, y), y, label=label)) +
  
  # Making the bars thin so that the emojis are visible
  
  geom_col(width = 0.1) + 
  
  # Creating emoji labels
  
  geom_text(family="EmojiOne", size=6, hjust = -0.05) +
  
  # Flipping axes so that the emoji labels can be read
  
  coord_flip() +
  
  # Setting y to go to zero for scale
  
  expand_limits(y = 0) + 
  
  # Relabelling
  
  scale_x_discrete(labels=c("â¤" = "heart", 
                            "\U0001f602" = "joy",
                            "\U0001f62d" = "sob",
                            "\U0001f496" = "sparking_heart",
                            "\U0001f970" = "smiling_face_with_hearts",
                            "\U0001f97a" = "pleading_face",
                            "\U0001f60d" = "heart_eyes",
                            "\U0001f624" = "triump")) +
  labs(
    title = "Most Common Top-Used Emojis Amongst Harvard Students",
    subtitle = "As determined by the top emoji placement of Apple's algorithm",
    x = "Emoji",
    y = "Frequency",
    caption = "See github for display of emojis on the graph; currently not supported in this format"
  ) + 
  theme_classic()
```
